Auto comment

diff --git a/ansible/roles/zfs-setup/tasks/main.yml b/ansible/roles/zfs-setup/tasks/main.yml
--- a/ansible/roles/zfs-setup/tasks/main.yml
+++ b/ansible/roles/zfs-setup/tasks/main.yml
@@ -305,11 +305,19 @@
     # Create a new boot entry in GPT 
     efibootmgr -d {{ target_device }} -v -c -l /EFI/fedora/shimx64.efi -L Fedora28
 
+  when: second_disk == true
+
+
+- name: Initialise /etc/fstab file to mount new locations
+  shell: | 
+    set -e   # prevent silent failures
+
     # Ensure the boot partition auto mounts onto /boot/efi at startup
     BLK_ID=$( blkid {{ boot_efi_partition }}  -o value | head -1 )
-    echo "UUID=${BLK_ID}       /boot/efi  vfat  umask=0077,shortname=winnt 0 2" >  /sysroot/etc/fstab
-    echo "pool/ROOT/fedora-28  /          zfs   default                    0 0" >> /sysroot/etc/fstab
-  when: second_disk == true
+    echo > /sysroot/etc/fstab <<HEREDOC
+      UUID=${BLK_ID}       /boot/efi  vfat  umask=0077,shortname=winnt 0 2
+      pool/ROOT/fedora-28  /          zfs   default                    0 0
+    HEREDOC
 
 - name: Allow Fedora:28+ to boot into zfs
   shell: |
